name: Automated Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        mkdir -p test_data/output
        python find_lowest_number.py test_data/test1_input.txt test_data/output/test1_output.txt
        python find_lowest_number.py test_data/test2_input.txt test_data/output/test2_output.txt
        python find_lowest_number.py test_data/test3_input.txt test_data/output/test3_output.txt

    - name: Compare outputs
      run: |
        diff -u test_data/output/test1_output.txt test_data/test1_expected.txt
        diff -u test_data/output/test2_output.txt test_data/test2_expected.txt
        diff -u test_data/output/test3_output.txt test_data/test3_expected.txt
